# Generated by Django 3.0.8 on 2020-08-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='city',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='country',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='website',
        ),
        migrations.AddField(
            model_name='book',
            name='in_possession',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='on_wishlist',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='read',
            field=models.BooleanField(default=0),
        ),
    ]
