# Generated by Django 3.0.8 on 2020-08-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0002_auto_20200803_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
