# Generated by Django 3.0.8 on 2020-08-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0003_book_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
