# Generated by Django 3.0.8 on 2020-08-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0005_auto_20200803_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='<django.db.models.fields.CharField> <django.db.models.fields.CharField>', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='EAN',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='URL',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(default='', max_length=200),
        ),
    ]
