# Generated by Django 3.0.8 on 2020-08-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0006_auto_20200806_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reading',
            field=models.BooleanField(default=0),
        ),
    ]
