# Generated by Django 3.0.8 on 2020-08-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0009_auto_20200806_1637'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'EAN')},
        ),
    ]
