# Generated by Django 3.0.8 on 2020-08-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0011_auto_20200806_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_acquired',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='date_read',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
