# Generated by Django 3.0.8 on 2020-08-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0012_auto_20200819_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_started_reading',
            field=models.DateField(null=True),
        ),
    ]
