# Generated by Django 3.0.8 on 2020-08-19 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0013_book_date_started_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
